In [67]:
#Backpropogation : it is a learning algorithm that allow a neural network to learn by adjusting weights based on the error(loss). 
#Steps : 
#1. Forward pass : 

In [68]:
#import libraries
import numpy as np 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras import regularizers

In [69]:
#use iris data
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler , LabelBinarizer

In [70]:

iris = load_iris()
x = iris.data
y=iris.target
print(x)
print(y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [71]:
#use labelbinarizer
data1 =LabelBinarizer()
y = data1.fit_transform(y)

In [72]:
#Normalize features
scalar=StandardScaler()
Scaled=scalar.fit_transform(x)

In [73]:
print(Scaled)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [74]:
X_train,X_test,y_train,y_test = train_test_split(Scaled,y,test_size=0.2,random_state=42)

In [75]:
y_test.shape

(30, 3)

In [76]:
X_train.shape

(120, 4)

In [77]:
import numpy as np 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras import regularizers


In [95]:
def model_creation():
    model = Sequential([
        Dense(10,input_shape=(4,),activation="relu"),
        Dense(3,activation="softmax")
    ])
    model.compile(optimizer=SGD(learning_rate=0.01),loss=CategoricalCrossentropy(),metrics=["accuracy"])
    return model

In [96]:
#model without backpropogation
model1 = model_creation()
pred1 = model1.predict(X_test)
pred1

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step


array([[0.33300996, 0.31848487, 0.3485051 ],
       [0.48995662, 0.3419922 , 0.16805117],
       [0.30323547, 0.33241233, 0.36435217],
       [0.34360155, 0.29775795, 0.35864052],
       [0.2892642 , 0.36484325, 0.34589258],
       [0.51055235, 0.24962342, 0.23982427],
       [0.3678879 , 0.29261357, 0.33949855],
       [0.30605778, 0.341449  , 0.3524932 ],
       [0.23806462, 0.2426588 , 0.5192767 ],
       [0.30639082, 0.2851488 , 0.40846038],
       [0.34806082, 0.3237277 , 0.32821146],
       [0.47668266, 0.17809384, 0.3452235 ],
       [0.4983648 , 0.26213932, 0.2394959 ],
       [0.46971363, 0.19153021, 0.33875626],
       [0.5896823 , 0.2757207 , 0.13459703],
       [0.3593892 , 0.3654882 , 0.27512258],
       [0.34203207, 0.25403467, 0.40393326],
       [0.30060965, 0.24906015, 0.45033026],
       [0.34676847, 0.28284052, 0.37039107],
       [0.32529646, 0.245857  , 0.42884654],
       [0.5395904 , 0.2015092 , 0.2589004 ],
       [0.34026206, 0.26367962, 0.39605832],
       [0.

In [97]:
#model with backpropogation
model2 = model_creation()
model2.fit(X_train,y_train,epochs= 100)
pred2 = model2.predict(X_test)
pred2

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5387 - loss: 1.0671  
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5829 - loss: 1.0222 
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5475 - loss: 1.0156 
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5615 - loss: 0.9768 
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5779 - loss: 0.9018 
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5738 - loss: 0.9011 
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.5590 - loss: 0.8451 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6158 - loss: 0.8346 
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5929 - loss: 0.8074 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5746 - loss: 0.7992 
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5875 - loss: 0.7854 
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6348 - lo

array([[5.3651895e-02, 5.1428860e-01, 4.3205947e-01],
       [8.8703817e-01, 9.0350442e-02, 2.2611408e-02],
       [4.8434676e-04, 1.4911295e-01, 8.5040265e-01],
       [6.2317554e-02, 4.4614699e-01, 4.9153545e-01],
       [2.7817221e-02, 5.6139910e-01, 4.1078377e-01],
       [8.9047968e-01, 9.0313643e-02, 1.9206656e-02],
       [2.3006254e-01, 5.4054493e-01, 2.2939256e-01],
       [1.5413912e-02, 2.5629315e-01, 7.2829294e-01],
       [7.9373149e-03, 6.4949447e-01, 3.4256825e-01],
       [9.8817006e-02, 6.4576250e-01, 2.5542048e-01],
       [3.1134069e-02, 2.2564933e-01, 7.4321657e-01],
       [9.2999500e-01, 6.3710578e-02, 6.2944423e-03],
       [9.1043681e-01, 7.4323602e-02, 1.5239619e-02],
       [9.3507141e-01, 5.8028735e-02, 6.8998849e-03],
       [9.4952101e-01, 4.3419167e-02, 7.0597543e-03],
       [1.0121296e-01, 3.0624932e-01, 5.9253770e-01],
       [6.5543987e-03, 1.3050546e-01, 8.6294013e-01],
       [8.1949584e-02, 7.0105827e-01, 2.1699212e-01],
       [6.8965450e-02, 4.675

In [98]:
loss,accuracy = model2.evaluate(X_test,y_test)
print(loss)
print(accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - accuracy: 0.9333 - loss: 0.3106
0.31061097979545593
0.9333333373069763


In [99]:
loss,accuracy = model1.evaluate(X_test,y_test)
print(loss)
print(accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 268ms/step - accuracy: 0.6667 - loss: 0.9837
0.9836669564247131
0.6666666865348816


In [100]:
#overfitting : If model is trained very much.
#underfitting : If model is not trained efficiently.

In [101]:
#How to avoid overfitting :
#1. Increase data size 
#2.Regularization : L1 and L2
#3. Dropout 
#How to avoid underfitting 
#1. Regularization
#2. Train model again and again 

In [ ]:
#What is DL
#DL layers or what is feed forward
#what is neural network
#what if flatten layer 
#what is dense layer 
#what is activation function : what is relu,tanh,softmax,sigmoid
#what is CNN and how we can import and use 
#what is simple RNN and LSTM and how we can import and use 
#what is filter in CNN
#what is optimizer  
#what is Backpropogation
#Why we need backpropogation and optimizer
#what is regularization and its techniques 
#what is overfitting and how to avoid it 
#what is underfitting and how to avoid it 
#What is dropout
#What is pixel (28*28) : 1D and 2D
#1D = 784
#What is convolutional layer , poooling , flattening , fully connected layer .

In [105]:
#ML
#1. Linear Regression
#2. Logistics Regression
#3. SVM : Classification / regression
#4. KNN
#5. Naive Bayes - GNB , MNB , BNB
#6. Random Forest Classifier 
#7. Decision Tree : Classification / regression

In [ ]:
#K-means : H - C : 3 methods 
#PCA
#