In [ ]:
#NLP : (Natural language processing )
# It is a branch of AI that helps computer to understand , interpret , geenerate human language,
#Without NLP :
#With NLP :

In [ ]:
#NLP Appllication :
#1. Search Engine
#2. Embedding
#3. Speech to test
#4. Language translation
#5. chatbots
#6. Grammer correction
#7. sentiment analysis

In [ ]:
#NLP steps :

#Tokenzation
#Remove Stopwards
#Stemming
#Vectorization
#Model Prediction

In [ ]:
#NLP is the best branch of AI
#Tokenization-------
#Basic input
#"NLP is the best branch of AI "
#After tokenization -
#"NLP" , "is" , "the" , "best" , "branch" , "of" , "AI".

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [ ]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [ ]:
from nltk.tokenize import word_tokenize
import nltk
# nltk.download('punkt_tab') # This was attempted but still resulted in an error
data = "NLP is the best branch of AI"
# Explicitly specify the language
processed_data = word_tokenize(data, language='english')
print(processed_data)

['NLP', 'is', 'the', 'best', 'branch', 'of', 'AI']


In [ ]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
Data1 = set(stopwords.words("english"))
Data2 =[]
for i in processed_data:
    if i.lower() not in Data1:
        Data2.append(i)
print(len(Data2))
print(Data2)

4
['NLP', 'best', 'branch', 'AI']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
#stemming :
from nltk.stem import PorterStemmer
Stemmer = PorterStemmer()

In [ ]:
data3 = [Stemmer.stem(i)]
for i in Data2 :
    s_words = Stemmer.stem(i)
    data3.append(s_words)
print(data3)


['ai', 'nlp', 'best', 'branch', 'ai']


In [ ]:
#Punctuation removal
import string
text = "Hello world! Python is amazing."
translator = str.maketrans("", "", string.punctuation)
text_without_punctuation = text.translate(translator)
print('original :',text)
print('Without Punctuation :',text_without_punctuation)

original : Hello world! Python is amazing.
Without Punctuation : Hello world Python is amazing


In [ ]:
#Vectorization
#Bag-of-words
from sklearn.feature_extraction.text import CountVectorizer
text = ["I have NLP book book" , "NLP book is in pdf format", "NLP is most important branch of an AI"]
vector = CountVectorizer()
New_text = vector.fit_transform(text)
print(vector.get_feature_names_out())
print(New_text.toarray())

['ai' 'an' 'book' 'branch' 'format' 'have' 'important' 'in' 'is' 'most'
 'nlp' 'of' 'pdf']
[[0 0 2 0 0 1 0 0 0 0 1 0 0]
 [0 0 1 0 1 0 0 1 1 0 1 0 1]
 [1 1 0 1 0 0 1 0 1 1 1 1 0]]


In [ ]:
#Tf -IDF
#How frequently they appear in the whole document
#How rare they are in the whole document
from sklearn.feature_extraction.text import TfidfVectorizer
text = ["I have NLP book book" , "NLP book is in pdf format", "NLP is most important branch of an AI"]
tfidf = TfidfVectorizer()
vectors = tfidf.fit_transform(text)
print(tfidf.get_feature_names_out())
print(vectors.toarray())

['ai' 'an' 'book' 'branch' 'format' 'have' 'important' 'in' 'is' 'most'
 'nlp' 'of' 'pdf']
[[0.         0.         0.7948031  0.         0.         0.52253528
  0.         0.         0.         0.         0.30861775 0.
  0.        ]
 [0.         0.         0.35829137 0.         0.4711101  0.
  0.         0.4711101  0.35829137 0.         0.27824521 0.
  0.4711101 ]
 [0.37994462 0.37994462 0.         0.37994462 0.         0.
  0.37994462 0.         0.28895767 0.37994462 0.22440141 0.37994462
  0.        ]]


In [ ]:
%pip install gensim

In [ ]:
#Embedding(Word2Vec , Glove )
#Word embedding maps each word to a vector of real numbers
import gensim.downloader as api
#model = api.load("word2vec-google-news-300")
model1 = api.load("glove-wiki-gigaword-50")
vector = model1["computer"]
print(vector[:10])
simi = model1.most_similar("computer", topn=5)
for i in simi:
    print(i)

[==================================================] 100.0% 66.0/66.0MB downloaded
[ 0.079084 -0.81504   1.7901    0.91653   0.10797  -0.55628  -0.84427
 -1.4951    0.13418   0.63627 ]
('computers', 0.9165045022964478)
('software', 0.8814992904663086)
('technology', 0.852556049823761)
('electronic', 0.812586784362793)
('internet', 0.8060455322265625)


In [ ]:
#Attention Mechanism  : It is a technique that allows a model to focus on specific work when performing a task .
#Why we need attention :
#Attention lets the model attend to all parts of the sequence even far a part of word.
#Type of Attention :
#1. Self Attention
#2. Global Attention
#3. Local Attention
#4. Multihead Attention
#Q - Query - What you want to know ?
#K - What each word effect ?
#V - What is each word represent ?

In [ ]:
pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 47.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 42.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 31.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 14.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 4.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 48.3 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstall

In [ ]:
#import required libraries -
import torch
import torch.nn as nn
import torch.functional as fn
text = ["The","Man","Work"]
e_d = 8


In [ ]:
#word to index
w_ix = {i:text.index(i) for i in text}
print(w_ix)

{'The': 0, 'Man': 1, 'Work': 2}


In [ ]:
w_idx={i:index for index , i in enumerate(text)}
print(w_idx)

{'The': 0, 'Man': 1, 'Work': 2}


In [ ]:
idx_to_word = torch.tensor([w_idx[i]for i in text])
idx_to_word

tensor([0, 1, 2])

In [ ]:
embed = nn.Embedding(num_embeddings=len(w_idx),embedding_dim=e_d)
embed

Embedding(3, 8)

In [ ]:
embeded = embed(idx_to_word)
print(embeded)


tensor([[-0.9544, -1.3771,  0.2512, -1.3847, -0.3246,  0.4320,  1.8594,  0.4273],
        [-0.6713,  2.0157, -0.1828,  1.5757, -0.6976, -0.3117, -0.1518,  1.7560],
        [ 0.5360,  0.0096, -1.4073, -0.4467,  0.4247, -1.0649, -1.1012,  1.0866]],
       grad_fn=<EmbeddingBackward0>)


In [ ]:
embeded =embeded.unsqueeze(0)
print(embeded)

tensor([[[-0.9544, -1.3771,  0.2512, -1.3847, -0.3246,  0.4320,  1.8594,
           0.4273],
         [-0.6713,  2.0157, -0.1828,  1.5757, -0.6976, -0.3117, -0.1518,
           1.7560],
         [ 0.5360,  0.0096, -1.4073, -0.4467,  0.4247, -1.0649, -1.1012,
           1.0866]]], grad_fn=<UnsqueezeBackward0>)


In [ ]:
num_head = 2
multi_head =nn.MultiheadAttention(embed_dim=e_d,num_heads=num_head,batch_first=True)
multi_head

MultiheadAttention(
  (out_proj): NonDynamicallyQuantizableLinear(in_features=8, out_features=8, bias=True)
)

In [ ]:
a_output , a_weight = multi_head(embeded,embeded,embeded)
print(a_output)
print(a_weight)

tensor([[[ 0.5253, -0.1830, -0.0552,  0.1145, -0.0019, -0.2041, -0.3739,
          -0.2278],
         [ 0.5760, -0.1897, -0.0816,  0.0758, -0.0039, -0.2742, -0.4863,
          -0.2806],
         [ 0.3216, -0.1432,  0.0617,  0.2608,  0.0308, -0.1665, -0.3991,
          -0.2519]]], grad_fn=<TransposeBackward0>)
tensor([[[0.3373, 0.3665, 0.2962],
         [0.2183, 0.4846, 0.2971],
         [0.3412, 0.2975, 0.3613]]], grad_fn=<MeanBackward1>)


In [ ]:
a_weight.squeeze(0).detach().numpy()

array([[0.3373286 , 0.36652082, 0.2961505 ],
       [0.21829917, 0.48463595, 0.29706484],
       [0.3412087 , 0.29749975, 0.36129156]], dtype=float32)

In [ ]:
a_output.squeeze(0).detach().numpy()

array([[ 0.52526736, -0.18300006, -0.05516355,  0.11446521, -0.00192033,
        -0.20405951, -0.3738522 , -0.22779602],
       [ 0.57596505, -0.18972541, -0.0815789 ,  0.07584693, -0.00386527,
        -0.27422753, -0.48634738, -0.28055933],
       [ 0.32155466, -0.14323156,  0.06168673,  0.26082554,  0.0307968 ,
        -0.16648802, -0.3990715 , -0.2518889 ]], dtype=float32)

In [ ]:
#Transformers- It follows a modular encoder and decoder design
#Encoder - (BERT model) Basically reads inout sentence and build a meaningful representation
#Decoder - (GPT model) Basically takes the representation and generate output
"The Man Work"

'The Man Work'

In [ ]:
pip install transformers sentencepiece

In [ ]:
import torch
from transformers import MarianMTModel, MarianTokenizer
model="Helsinki-NLP/opus-mt-en-hi"
tok=MarianTokenizer.from_pretrained(model)
models = MarianMTModel.from_pretrained(model)
input_text=["the man work"]
tok_input = tok(input_text, return_tensors="pt",padding=True , truncation=True) # Use the tokenizer and specify "pt" for PyTorch tensors
print(tok_input)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/44.0 [00:00<?, ?B/s]

source.spm:   0%|          | 0.00/812k [00:00<?, ?B/s]

target.spm:   0%|          | 0.00/1.07M [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

config.json: 0.00B [00:00, ?B/s]

/usr/local/lib/python3.11/dist-packages/transformers/models/marian/tokenization_marian.py:175: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")


pytorch_model.bin:   0%|          | 0.00/306M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/293 [00:00<?, ?B/s]

{'input_ids': tensor([[  4, 259, 352,   0]]), 'attention_mask': tensor([[1, 1, 1, 1]])}


In [ ]:
translate = models.generate(**tok_input)

model.safetensors:   0%|          | 0.00/306M [00:00<?, ?B/s]

In [ ]:
translate

tensor([[61949,  1026,   182,   161,     5,     0]])

In [ ]:
#decode --
output = tok.batch_decode(translate,skip_special_tokens=True)
print(output)

['आदमी काम करता है']


In [ ]:
#pytorch
#tensorflow
#keras
#nltk
#transformer - part of hugging library
#gensim
#lengdetect
#opencv
#pil
#torchvision

In [ ]:
#face detection mask using opencv