In [12]:
#NLP : (Natural language processing ) 
# It is a branch of AI that helps computer to understand , interpret , geenerate human language, 
#Without NLP : 
#With NLP : 

In [13]:
#NLP Appllication : 
#1. Search Engine 
#2. Embedding
#3. Speech to test 
#4. Language translation 
#5. chatbots 
#6. Grammer correction
#7. sentiment analysis 

In [14]:
#NLP steps :

#Tokenzation 
#Remove Stopwards
#Stemming
#Vectorization 
#Model Prediction 

In [15]:
#NLP is the best branch of AI 
#Tokenization-------
#Basic input 
#"NLP is the best branch of AI "
#After tokenization -
#"NLP" , "is" , "the" , "best" , "branch" , "of" , "AI".

In [9]:
#nltk is a python library that is used for processing human language data 
import nltk
nltk.download("punkt")


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [12]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
data = "NLP is the best branch of AI"
processed_data = word_tokenize(data)
print(processed_data)

LookupError: 
**********************************************************************
  Resource punkt_tab not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt_tab/english/

  Searched in:
    - 'C:\\Users\\hp/nltk_data'
    - 'c:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\nltk_data'
    - 'c:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\share\\nltk_data'
    - 'c:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python39\\lib\\nltk_data'
    - 'C:\\Users\\hp\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************


In [18]:
from nltk.corpus import stopwards 
Data1 = set(stopwards.words("english"))
Data2 =[]
for i in Processed_Data:
    if i.lower() not in detail:
        Data2.append(processed_data)
print(len(Data2))

ImportError: cannot import name 'stopwards' from 'nltk.corpus' (c:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\nltk\corpus\__init__.py)

In [19]:
#stemming : 
from nltk.stem import PorterStemmer
Stemmer = PorterStemmer()

In [20]:
data3 = [Stemmer.stem(i)]
for i in Data2 :
    s_words = Stemmer.stem(i)
    data3.append(s_words)
print(data3)




NameError: name 'i' is not defined

In [26]:
#Vectorization
#Bag-of-words
from sklearn.feature_extraction.text import CountVectorizer
text = ["I have NLP book book" , "NLP book is in pdf format", "NLP is most important branch of an AI"]
vector = CountVectorizer()
New_text = vector.fit_transform(text)
print(vector.get_feature_names_out())
print(New_text.toarray())

['ai' 'an' 'book' 'branch' 'format' 'have' 'important' 'in' 'is' 'most'
 'nlp' 'of' 'pdf']
[[0 0 2 0 0 1 0 0 0 0 1 0 0]
 [0 0 1 0 1 0 0 1 1 0 1 0 1]
 [1 1 0 1 0 0 1 0 1 1 1 1 0]]


In [27]:
#Tf -IDF
#How frequently they appear in the whole document 
#How rare they are in the whole document 
from sklearn.feature_extraction.text import TfidfVectorizer
text = ["I have NLP book book" , "NLP book is in pdf format", "NLP is most important branch of an AI"]
tfidf = TfidfVectorizer()
vectors = tfidf.fit_transform(text)
print(tfidf.get_feature_names_out())
print(vectors.toarray())

['ai' 'an' 'book' 'branch' 'format' 'have' 'important' 'in' 'is' 'most'
 'nlp' 'of' 'pdf']
[[0.         0.         0.7948031  0.         0.         0.52253528
  0.         0.         0.         0.         0.30861775 0.
  0.        ]
 [0.         0.         0.35829137 0.         0.4711101  0.
  0.         0.4711101  0.35829137 0.         0.27824521 0.
  0.4711101 ]
 [0.37994462 0.37994462 0.         0.37994462 0.         0.
  0.37994462 0.         0.28895767 0.37994462 0.22440141 0.37994462
  0.        ]]


In [2]:
#Embedding(Word2Vec , Glove )
#Word embedding maps each word to a vector of real numbers 
import gensim.downloader as api
#model = api.load("word2vec-google-news-300")
model1 = api.load("glove-wiki-gigaword-50")
vector = model1["computer"]
print(vector[:10])
simi = model1.most_similar("computer", topn=5)
for i in simi:
    print(i)

[ 0.079084 -0.81504   1.7901    0.91653   0.10797  -0.55628  -0.84427
 -1.4951    0.13418   0.63627 ]
('computers', 0.9165045022964478)
('software', 0.8814992904663086)
('technology', 0.852556049823761)
('electronic', 0.812586784362793)
('internet', 0.8060455322265625)


In [4]:
#Attention Mechanism  : It is a technique that allows a model to focus on specific work when performing a task .
#Why we need attention : 
#Attention lets the model attend to all parts of the sequence even far a part of word.
#Type of Attention :
#1. Self Attention 
#2. Global Attention
#3. Local Attention 
#4. Multihead Attention
#Q - Query - What you want to know ?
#K - What each word effect ?
#V - What is each word represent ?

In [ ]:
#Attention Mechanism 
import 